-- PostgreSQL tables

-- Schema Version: 0.1.0
-- Last Modified: 2025-05-23

CREATE TABLE IF NOT EXISTS books (
    book_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
);

CREATE TABLE IF NOT EXISTS publishers (
    publisher_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS authors (
    author_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bio TEXT
);

CREATE TABLE IF NOT EXISTS series (
    book_id INT NOT NULL,
    author_id INT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors(author_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS books (
    book_id INT NOT NULL,
    series_id INT NOT NULL,
    PRIMARY KEY (book_id, series_id),
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE,
    FOREIGN KEY (series_id) REFERENCES series(book_id) ON DELETE CASCADE
);